# Generated by Django 3.2.16 on 2022-12-07 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'ação do jogo', 'verbose_name_plural': 'ações dos jogos'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'partida', 'verbose_name_plural': 'partida'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'jogador', 'verbose_name_plural': 'jogadores'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'time', 'verbose_name_plural': 'times'},
        ),
        migrations.AlterField(
            model_name='action',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='core.match', verbose_name='partida'),
        ),
        migrations.AlterField(
            model_name='action',
            name='minutes',
            field=models.PositiveSmallIntegerField(verbose_name='minutos'),
        ),
        migrations.AlterField(
            model_name='action',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='core.player', verbose_name='jogador'),
        ),
        migrations.AlterField(
            model_name='action',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='core.team', verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_a_matches', to='core.team', verbose_name='time A'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a_goal',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='gol(s) do time A'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_b_matches', to='core.team', verbose_name='time B'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b_goal',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='gol(s) do time B'),
        ),
    ]
